version: "3.9"

networks:
  carbigdata-network:
    driver: bridge
    
services:
  carbigdata-minio:
    image: quay.io/minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
     - "9000:9000"
     - "9001:9001"
    networks:
     - carbigdata-network
    volumes:
     - type: bind
       source: ./data
       target: /mnt/data
    command: server --console-address ":9001" /mnt/data

  carbigdata-postgres:
    image: postgres
    ports:
     - "5432:5432"
    networks:
     - carbigdata-network
    volumes:
     - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: admin
     POSTGRES_DB: carbigdata
      
  carbigdata-api:
    build:
     context: .
     dockerfile: Dockerfile
    command: ["/wait-for-it.sh", "carbigdata-postgres:5432", "-t", "30", "--", "java", "-jar", "app.jar"]
    environment:
      DB_HOST: carbigdata-postgres
      STORAGE_HOST: carbigdata-minio
      MINIO_ACCESS_KEY: 8PmrhM6vcR4n88GgJ94J
      MINIO_ACCESS_SECRET: vAbRt6t9Km3eL2wLEMpn5BJFqOc7lkdye63bif4x
    ports:
      - "8080:8080"
    networks:
      - carbigdata-network
    depends_on:
      - carbigdata-postgres
      - carbigdata-minio